[project]
name = "shared"
version = "0.1.0"
description = "Package shared across the workspace"
readme = "README.md"
dependencies = []


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
