channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pytest=7.4.0
  - pip:
    # cleaner scripts than using argparse
    - func-to-script==0.1.0
    # minimum mlflow packages required for logging in AzureML
    - azureml-mlflow==1.53.0
    - mlflow-skinny==2.6.0
